// Canonical CustomReskin loader, shipped verbatim inside every generated pack.
// Keep in sync with /home/virtualized/Projects/BMP/CustomReskin/core.lua.

export const CORE_LUA = `--- CustomReskin loader (per-object).
--
-- Ships no game art or text. A pack generated by the BMP Reskin Studio drops:
--   * data/manifest.lua  -> packed atlases + per-object atlas/pos rebinds
--   * assets/{1x,2x}/...  -> the packed sprite sheets
--   * localization/*.lua  -> SMODS auto-loads; overrides matching vanilla keys
--
-- Mechanism: for each replaced object we register a fresh packed atlas and point
-- that object's registry entry (G.P_CENTERS / G.P_BLINDS / G.P_TAGS / G.P_SEALS /
-- G.P_STAKES) at it. Untouched objects keep their vanilla art and no base assets
-- are needed. Grid atlases (playing cards, chips, shop sign) are composed full
-- sheets applied as raw overrides. Empty pack = no-op.

local mod = SMODS.current_mod

local function load_optional(rel)
	local ok, chunk = pcall(SMODS.load_file, rel)
	if not ok or type(chunk) ~= 'function' then return nil end
	local ran, res = pcall(chunk)
	if not ran then
		sendWarnMessage('CustomReskin: failed to run ' .. rel .. ': ' .. tostring(res), 'CustomReskin')
		return nil
	end
	return res
end

local manifest = load_optional('data/manifest.lua') or {}
local atlases = manifest.atlases or {}
local objects = manifest.objects or {}
local sounds = manifest.sounds or {}
local shaders = manifest.shaders or {}
local icon = manifest.icon

local function prefixed(key)
	return ((mod.prefix and mod.prefix ~= '') and (mod.prefix .. '_') or '') .. key
end

-- 1) Register every packed/override atlas. \`raw\` keeps the vanilla key so grid
--    atlases (cards_1, chips, shop_sign) replace the base sheet in place; packed
--    category atlases get the mod prefix and are referenced by the rebinds below.
for _, a in ipairs(atlases) do
	SMODS.Atlas({
		key = a.key,
		raw_key = a.raw or nil,
		path = a.path,
		px = a.px,
		py = a.py,
		frames = a.frames,
		fps = a.fps,
		atlas_table = a.atlas_table or 'ASSET_ATLAS',
	})
end

-- Mod-list icon. Steamodded shows the \`<prefix>_modicon\` atlas next to the mod in
-- its menu; registering it (key \`modicon\` gets the prefix) is enough. Optional, so
-- empty packs stay iconless rather than referencing a missing file.
if icon and icon.path then
	SMODS.Atlas({
		key = 'modicon',
		path = icon.path,
		px = icon.px,
		py = icon.py,
		frames = icon.frames,
		atlas_table = icon.frames and 'ANIMATION_ATLAS' or 'ASSET_ATLAS',
	})
end

-- 2) Repoint each replaced object at its packed atlas + cell. Deferred until the
--    vanilla prototype tables exist (they normally do at mod-load, but guard it).
local REGISTRY = {
	P_CENTERS = function() return G.P_CENTERS end,
	P_BLINDS = function() return G.P_BLINDS end,
	P_TAGS = function() return G.P_TAGS end,
	P_SEALS = function() return G.P_SEALS end,
	P_STAKES = function() return G.P_STAKES end,
}

local function apply_object(o)
	local get = REGISTRY[o.registry]
	local tbl = get and get()
	local entry = tbl and tbl[o.key]
	if not entry then return false end
	entry.atlas = prefixed(o.atlas)
	entry.pos = { x = o.x or 0, y = o.y or 0 }
	if o.soul_atlas then
		entry.soul_atlas = prefixed(o.soul_atlas)
		entry.soul_pos = { x = o.soul_x or 0, y = o.soul_y or 0 }
	end
	return true
end

local function apply_all()
	for _, o in ipairs(objects) do
		pcall(apply_object, o)
	end
end

if #objects > 0 then
	if G and G.P_CENTERS then
		apply_all()
	else
		-- Registries not ready yet: apply once on the first game update.
		local orig_update = Game.update
		function Game:update(dt)
			orig_update(self, dt)
			if not mod._reskin_applied and G and G.P_CENTERS then
				mod._reskin_applied = true
				apply_all()
			end
		end
	end
end

-- 3) Sound replacements.
for _, s in ipairs(sounds) do
	SMODS.Sound({ key = s.key, path = s.path, replace = s.replace or s.key })
end

-- 4) Default shaders. Give specific cards a built-in shader effect (purely
--    visual, no scoring), applied by vanilla center key via one draw step -- the
--    same mechanism the base game uses for e.g. the Invisible Joker's shader.
--    \`gold_seal\` reuses the \`voucher\` shader; \`negative\` also draws the shine
--    overlay; \`vortex\` needs its flag set for the shader's time uniforms.
if #shaders > 0 and SMODS and SMODS.DrawStep then
	local by_key = {}
	for _, s in ipairs(shaders) do
		by_key[s.key] = s.shader
	end
	local ALIAS = { gold_seal = 'voucher' }
	local function center_key(card)
		local c = card.config
		return c and (c.center_key or (c.center and c.center.key))
	end
	SMODS.DrawStep({
		key = 'reskin_shader',
		order = 21, -- just after the edition step (order 20)
		func = function(self, layer)
			local raw = by_key[center_key(self)]
			if not raw then return end
			local name = ALIAS[raw] or raw
			if raw == 'vortex' then self.vortex = true end
			local send = self.ARGS and self.ARGS.send_to_shader
			self.children.center:draw_shader(name, nil, send)
			if raw == 'negative' then
				self.children.center:draw_shader('negative_shine', nil, send)
			end
			local hide_front = self.should_hide_front and self:should_hide_front()
			if self.children.front and not hide_front then
				self.children.front:draw_shader(name, nil, send)
				if raw == 'negative' then
					self.children.front:draw_shader('negative_shine', nil, send)
				end
			end
		end,
	})
end
`
