-- Launcher release management, copied from the old site. The launcher polls
-- the public GET /api/releases endpoint; admins manage rows via /api/webadmin.
CREATE TABLE IF NOT EXISTS "mod_branches" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp with time zone NOT NULL DEFAULT now(),
	CONSTRAINT "mod_branches_name_unique" UNIQUE("name")
);

CREATE TABLE IF NOT EXISTS "mod_release" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"version" text NOT NULL,
	"url" text NOT NULL,
	"smods_version" text DEFAULT 'latest',
	"lovely_version" text DEFAULT 'latest',
	"branch_id" integer NOT NULL DEFAULT 1,
	"created_at" timestamp with time zone NOT NULL DEFAULT now(),
	"updated_at" timestamp with time zone NOT NULL DEFAULT now()
);

DO $$ BEGIN
	ALTER TABLE "mod_release" ADD CONSTRAINT "mod_release_branch_id_mod_branches_id_fk"
		FOREIGN KEY ("branch_id") REFERENCES "public"."mod_branches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;

-- Seed default branches and advance the identity sequence past the explicit ids.
INSERT INTO "mod_branches" ("id", "name") VALUES (1, 'main'), (2, 'beta')
	ON CONFLICT DO NOTHING;
ALTER TABLE "mod_branches" ALTER COLUMN "id" RESTART WITH 3;
