-- Launcher release hosting -- replaces the old mod_release/mod_branches
-- ("Balatro Multiplayer Launcher" self-update channel, which pointed at
-- external GitHub-asset URLs and stored no files of its own) with a system
-- for the new, privately-hosted launcher: one launcher_release row per
-- version, launcher_release_asset rows for each platform's uploaded binary
-- (path relative to LAUNCHER_RELEASES_DIR on disk, plus size/sha256 for the
-- launcher to verify its download). Old rows point at a retired URL scheme
-- with no successor -- dropped, not migrated.
CREATE TYPE "launcher_platform" AS ENUM ('windows', 'mac', 'linux');

CREATE TABLE "launcher_release" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"version" varchar(64) NOT NULL UNIQUE,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "launcher_release_asset" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"release_id" integer NOT NULL REFERENCES "launcher_release"("id") ON DELETE CASCADE,
	"platform" "launcher_platform" NOT NULL,
	"storage_path" text NOT NULL,
	"original_filename" text NOT NULL,
	"file_size" integer NOT NULL,
	"sha256" varchar(64) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX "launcher_release_asset_release_platform_idx" ON "launcher_release_asset" ("release_id", "platform");

DROP TABLE "mod_release";
DROP TABLE "mod_branches";
