-- Patch notes / news posts, authored via the admin Blog page (Tiptap
-- editor, HTML sanitized server-side before it ever reaches this table)
-- and pulled by the launcher's GET /api/blog/latest. status/published_at
-- is a deliberate two-column draft/publish model: publishing always bumps
-- published_at to now (so an unpublish-then-republish can become "latest"
-- again), while unpublishing only flips status back to 'draft' and leaves
-- published_at alone.
CREATE TYPE "blog_post_kind" AS ENUM ('patch_notes', 'news');
CREATE TYPE "blog_post_status" AS ENUM ('draft', 'published');

CREATE TABLE IF NOT EXISTS "blog_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"kind" "blog_post_kind" NOT NULL,
	"title" varchar(200) NOT NULL,
	"body_html" text NOT NULL,
	"status" "blog_post_status" DEFAULT 'draft' NOT NULL,
	"published_at" timestamp with time zone,
	"author_player_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
