// Re-import a previously generated CustomReskin ZIP to keep editing it.

import { emptyProject, type ObjectEdit, type ProjectState } from './types'
import { readZip, unzipText } from './zip'
import { PROJECT_FILE_NAME } from './generate'

/** Bring an older (schema 2) project up to schema 3 by seeding each still's
 *  `base`/`render` from its final sprite, so the render toggles are editable. */
function toSchema3(p: ProjectState): ProjectState {
  const objects: Record<string, ObjectEdit> = {}
  for (const [id, e] of Object.entries(p.objects)) {
    objects[id] =
      e.base === undefined && e.sprites.length === 1
        ? { ...e, base: e.sprites[0], render: e.render ?? {} }
        : e
  }
  return { ...p, schema: 3, objects }
}

export async function importPack(file: File): Promise<ProjectState> {
  const buf = new Uint8Array(await file.arrayBuffer())
  const files = readZip(buf)

  const projectBytes = files.get(PROJECT_FILE_NAME)
  if (projectBytes) {
    const parsed = JSON.parse(unzipText(projectBytes)) as ProjectState
    // The on-disk schema may predate the current literal; read it as a number.
    const schema = (parsed as { schema?: number }).schema
    if (parsed && (schema === 2 || schema === 3)) {
      // merge over defaults so packs missing fields still load
      return toSchema3({ ...emptyProject(), ...parsed, schema: 3 })
    }
  }

  throw new Error(
    `This ZIP has no ${PROJECT_FILE_NAME}. Only packs generated by the Reskin Studio can be re-imported.`
  )
}
