// Re-import a previously generated CustomReskin ZIP to keep editing it.

import { emptyProject, type ProjectState } from './types'
import { readZip, unzipText } from './zip'
import { PROJECT_FILE_NAME } from './generate'

export async function importPack(file: File): Promise<ProjectState> {
  const buf = new Uint8Array(await file.arrayBuffer())
  const files = readZip(buf)

  const projectBytes = files.get(PROJECT_FILE_NAME)
  if (projectBytes) {
    const parsed = JSON.parse(unzipText(projectBytes)) as ProjectState
    if (parsed && parsed.schema === 2) {
      // merge over defaults so packs missing fields still load
      return { ...emptyProject(), ...parsed }
    }
  }

  throw new Error(
    `This ZIP has no ${PROJECT_FILE_NAME}. Only packs generated by the Reskin Studio can be re-imported.`
  )
}
