[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''if self.STATE == self.STATES.MENU then
            self:update_menu(dt)
        end'''
position = 'after'
payload = '''
    if self.STATE == self.STATES.WAITING_ON_ANTE_INFO then
      MP.update_waiting_on_ante_info(dt)
    end
    
    if self.STATE == self.STATES.WAITING_ON_PVP_END then
      MP.update_waiting_on_pvp_end(dt)
    end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self.GAME.round_resets.blind_choices.Boss = get_new_boss()'''
position = 'at'
payload = '''self.GAME.round_resets.blind_choices.Boss = MP.is_in_lobby() and self.GAME.round_resets.blind_choices.Boss or get_new_boss()'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self:prep_stage(G.STAGES.RUN, saveTable and saveTable.STATE or G.STATES.BLIND_SELECT)'''
position = 'at'
payload = '''self:prep_stage(G.STAGES.RUN, saveTable and saveTable.STATE or MP.is_in_lobby() and G.STATES.WAITING_ON_ANTE_INFO or G.STATES.BLIND_SELECT)'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = '''G.GAME.round_resets.blind_choices.Boss = get_new_boss()'''
position = 'at'
payload = '''G.GAME.round_resets.blind_choices.Boss = MP.is_in_lobby() and G.GAME.round_resets.blind_choices.Boss or get_new_boss()'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''G.GAME.round_resets.blind_choices.Boss = get_new_boss()'''
position = 'at'
payload = '''G.GAME.round_resets.blind_choices.Boss = MP.is_in_lobby() and G.GAME.round_resets.blind_choices.Boss or get_new_boss()'''
match_indent = true
times = 2

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''local main_menu = nil'''
position = 'after'
payload = '''local leave_lobby = nil'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''main_menu = UIBox_button{ label = {localize('b_main_menu')}, button = "go_to_menu", minw = 5}'''
position = 'after'
payload = '''leave_lobby = UIBox_button{ label = {localize('b_leave_lobby')}, button = "mp_leave_lobby", minw = 5}'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''restart,
      main_menu,'''
position = 'at'
payload = '''not MP.is_in_lobby() and restart or nil,
      not MP.is_in_lobby() and main_menu or nil,
      MP.is_in_lobby() and leave_lobby or nil,'''
match_indent = true
times = 1