[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483647

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''if self.STATE == self.STATES.MENU then
            self:update_menu(dt)
        end'''
position = 'after'
payload = '''
    if self.STATE == self.STATES.WAITING_ON_ANTE_INFO then
      MP.update_waiting_on_ante_info(dt)
    end
    
    if self.STATE == self.STATES.WAITING_ON_PVP_END then
      MP.update_waiting_on_pvp_end(dt)
    end'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self.GAME.round_resets.blind_choices.Boss = get_new_boss()'''
position = 'at'
payload = '''self.GAME.round_resets.blind_choices.Boss = MP.is_in_lobby() and self.GAME.round_resets.blind_choices.Boss or get_new_boss()'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''self:prep_stage(G.STAGES.RUN, saveTable and saveTable.STATE or G.STATES.BLIND_SELECT)'''
position = 'at'
payload = '''self:prep_stage(G.STAGES.RUN, saveTable and saveTable.STATE or MP.is_in_lobby() and G.STATES.WAITING_ON_ANTE_INFO or G.STATES.BLIND_SELECT)'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'function/common_events.lua'
pattern = '''G.GAME.round_resets.blind_choices.Boss = get_new_boss()'''
position = 'at'
payload = '''G.GAME.round_resets.blind_choices.Boss = MP.is_in_lobby() and G.GAME.round_resets.blind_choices.Boss or get_new_boss()'''
match_indent = true
times = 1